# Changes here will be overwritten by Copier
_commit: v0.2.5
_src_path: gh:deeplex/copier-cpp
buildver: 0.1.0.2
email: henrik@gassmann.onl
full_name: Henrik Steffen Gaßmann
header_only: false
namespace: dp
project_name: deeppack
project_slug: deeppack
semver: 0.1.0-alpha.3
year: 2020-2023

