# Changes here will be overwritten by Copier
_commit: v0.3.3
_src_path: gh:deeplex/copier-cpp
email: henrik@gassmann.onl
full_name: Henrik Steffen Gaßmann
header_config: true
header_only: false
namespace: dp
project_name: deeppack
project_slug: deeppack
workaround_header: true
year: 2020-2023
